In [1]:
import pandas as pd

In [2]:
# Change the filename if you aren't in the same directory

file_name = "nfl_stats.xlsx"

# Read in the file from excel
df = pd.read_excel(file_name)

# Don't worry about this - we are just removing the special characters
df['Player'] = df['Player'].str.replace("*", "")
df['Player'] = df['Player'].str.replace("+", "")

In [3]:
df.head()

,Rk,Player,Tm,Age,Pos,G,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sk
0,1,Ben Roethlisberger,PIT,36,QB,16,16,452,675,67.0,5129,34,16,7.6,11.3,320.6,96.5,71.0,24
1,2,Andrew Luck,IND,29,QB,16,16,430,639,67.3,4593,39,15,7.2,10.7,287.1,98.7,69.4,18
2,3,Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42
3,4,Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40
4,5,Aaron Rodgers,GNB,35,QB,16,16,372,597,62.3,4442,25,2,7.4,11.9,277.6,97.6,54.4,49

In [4]:
# This makes things ugly
print(df)

      Rk               Player   Tm  Age    Pos   G  GS  Cmp  Att   Cmp%   Yds  \
0      1   Ben Roethlisberger  PIT   36     QB  16  16  452  675   67.0  5129
1      2          Andrew Luck  IND   29     QB  16  16  430  639   67.3  4593
2      3            Matt Ryan  ATL   33     QB  16  16  422  608   69.4  4924
3      4         Kirk Cousins  MIN   30     QB  16  16  425  606   70.1  4298
4      5        Aaron Rodgers  GNB   35     QB  16  16  372  597   62.3  4442
5      6          Case Keenum  DEN   30     QB  16  16  365  586   62.3  3890
6      7      Patrick Mahomes  KAN   23     QB  16  16  383  580   66.0  5097
7      8          Eli Manning  NYG   37     QB  16  16  380  576   66.0  4299
8      9            Tom Brady  NWE   41     QB  16  16  375  570   65.8  4355
9     10           Jared Goff  LAR   24     QB  16  16  364  561   64.9  4688
10    11     Matthew Stafford  DET   30     QB  16  16  367  555   66.1  3777
11    12           Derek Carr  OAK   27     QB  16  16  381  553   68.9  4049
12    13         Dak Prescott  DAL   25     QB  16  16  356  526   67.7  3885
13    14        Philip Rivers  LAC   37     QB  16  16  347  508   68.3  4308
14    15       Deshaun Watson  HOU   23     QB  16  16  345  505   68.3  4165
15    16           Drew Brees  NOR   39     QB  15  15  364  489   74.4  3992
16    17       Baker Mayfield  CLE   23     QB  14  13  310  486   63.8  3725
17    18           Cam Newton  CAR   29     QB  14  14  320  471   67.9  3395
18    19    Mitchell Trubisky  CHI   24     QB  14  14  289  434   66.6  3223
19    20       Russell Wilson  SEA   30     QB  16  16  280  427   65.6  3448
20    21          Sam Darnold  NYJ   21     QB  13  13  239  414   57.7  2865
21    22        Blake Bortles  JAX   26     QB  13  12  243  403   60.3  2718
22    23         Carson Wentz  PHI   26     QB  11  11  279  401   69.6  3074
23    24           Josh Rosen  ARI   21     QB  14  13  217  393   55.2  2278
24    25           Joe Flacco  BAL   33     QB   9   9  232  379   61.2  2465
25    26       Jameis Winston  TAM   24     QB  11   9  244  378   64.6  2992
26    27          Andy Dalton  CIN   31     QB  11  11  226  365   61.9  2566
27    28       Marcus Mariota  TEN   25     QB  14  13  228  331   68.9  2528
28    29           Alex Smith  WAS   34     QB  10  10  205  328   62.5  2180
29    30           Josh Allen  BUF   22     QB  12  11  169  320   52.8  2074
..   ...                  ...  ...  ...    ...  ..  ..  ...  ...    ...   ...
76    77       Nelson Agholor  PHI   25     WR  16  16    1    1  100.0    15
77    78       Danny Amendola  MIA   33     WR  15  15    1    1  100.0    28
78    79          Bryan Anger  TAM   30      P  16   0    0    1    0.0     0
79    80         Cole Beasley  DAL   29     wr  16   4    0    1    0.0     0
80    81      Corey Bojorquez  BUF   22      P   8   0    0    1    0.0     0
81    82        Chris Boswell  PIT   27      K  15   0    1    1  100.0     2
82    83           Tyler Boyd  CIN   24     WR  14  14    0    1    0.0     0
83    84        Antonio Brown  PIT   30     WR  15  15    0    1    0.0     0
84    85          Kevin Byard  TEN   25     FS  16  16    1    1  100.0    66
85    86          Tarik Cohen  CHI   23  rb/wr  16   7    1    1  100.0     1
86    87          Logan Cooke  JAX   23      P  16   0    1    1  100.0     4
87    88           Eric Ebron  IND   25  te/wr  16   8    0    1    0.0     0
88    89      Bruce Ellington  2TM   27    NaN   7   3    0    1    0.0     0
89    90     Larry Fitzgerald  ARI   35     WR  16  16    1    1  100.0    32
90    91    Dontrell Hilliard  CLE   23    NaN  11   0    0    1    0.0     0
91    92      DeAndre Hopkins  HOU   26     WR  16  16    0    1    0.0     0
92    93      Darius Jennings  TEN   26    NaN  16   0    1    1  100.0    21
93    94            Zay Jones  BUF   23     WR  16  15    0    1    0.0     0
94    95             Sam Koch  BAL   36      P  16   0    1    1  100.0    21
95    96  Christian McCaffrey  CAR   22     RB  16  16    1    1  100.0    50
96    97       Anthony Miller  CHI   24     wr  15   4    1    1  100.0     8
97    98          Matt Prater  DET   34      K  16   0    1    1  100.0     8
98    99     Emmanuel Sanders  DEN   31     WR  12  12    1    1  100.0    28
99   100             JK Scott  GNB   22      P  16   0    0    1    0.0     0
100  101         Kenny Stills  MIA   26     WR  15  15    1    1  100.0     3
101  102         Logan Thomas  BUF   27     te  12   3    1    1  100.0    15
102  103         Colby Wadman  DEN   23      P  12   0    1    1  100.0    12
103  104            Tress Way  WAS   28      P  16   0    1    1  100.0     7
104  105       Dede Westbrook  JAX   25     WR  16   9    0    1    0.0     0
105  106        Albert Wilson  MIA   26     wr   7   3    1    1  100.0    52

     TD  Int   Y/A   Y/C    Y/G   Rate    QBR  Sk
0    34   16   7.6  11.3  320.6   96.5   71.0  24
1    39   15   7.2  10.7  287.1   98.7   69.4  18
2    35    7   8.1  11.7  307.8  108.1   68.5  42
3    30   10   7.1  10.1  268.6   99.7   58.2  40
4    25    2   7.4  11.9  277.6   97.6   54.4  49
5    18   15   6.6  10.7  243.1   81.2   45.5  34
6    50   12   8.8  13.3  318.6  113.8   80.4  26
7    21   11   7.5  11.3  268.7   92.4   48.7  47
8    29   11   7.6  11.6  272.2   97.7   66.6  21
9    32   12   8.4  12.9  293.0  101.1   63.1  33
10   21   11   6.8  10.3  236.1   89.9   48.4  40
11   19   10   7.3  10.6  253.1   93.9   46.9  51
12   22    8   7.4  10.9  242.8   96.9   56.2  56
13   32   12   8.5  12.4  269.3  105.5   69.1  32
14   26    9   8.2  12.1  260.3  103.1   60.7  62
15   32    5   8.2  11.0  266.1  115.7   80.4  17
16   27   14   7.7  12.0  266.1   93.7   53.2  25
17   24   13   7.2  10.6  242.5   94.2   55.0  29
18   24   12   7.4  11.2  230.2   95.4   70.8  24
19   35    7   8.1  12.3  215.5  110.9   62.8  51
20   17   15   6.9  12.0  220.4   77.6   45.5  30
21   13   11   6.7  11.2  209.1   79.8   41.7  31
22   21    7   7.7  11.0  279.5  102.2   62.6  31
23   11   14   5.8  10.5  162.7   66.7   24.7  45
24   12    6   6.5  10.6  273.9   84.2   56.3  16
25   19   14   7.9  12.3  272.0   90.2   69.7  27
26   21   11   7.0  11.4  233.3   89.6   62.3  21
27   11    8   7.6  11.1  180.6   92.3   50.6  42
28   10    5   6.6  10.6  218.0   85.7   51.4  22
29   10   12   6.5  12.3  172.8   67.9   49.8  28
..   ..  ...   ...   ...    ...    ...    ...  ..
76    0    0  15.0  15.0    0.9  118.7  100.0   0
77    1    0  28.0  28.0    1.9  158.3  100.0   0
78    0    0   0.0   NaN    0.0   39.6    NaN   0
79    0    0   0.0   NaN    0.0   39.6   27.6   0
80    0    0   0.0   NaN    0.0   39.6    NaN   0
81    1    0   2.0   2.0    0.1  118.7    NaN   0
82    0    0   0.0   NaN    0.0   39.6    2.8   0
83    0    0   0.0   NaN    0.0   39.6    2.8   0
84    1    0  66.0  66.0    4.1  158.3    NaN   0
85    1    0   1.0   1.0    0.1  118.7  100.0   0
86    0    0   4.0   4.0    0.3   83.3    NaN   0
87    0    0   0.0   NaN    0.0   39.6    0.0   0
88    0    0   0.0   NaN    0.0   39.6    NaN   0
89    1    0  32.0  32.0    2.0  158.3  100.0   0
90    0    1   0.0   NaN    0.0    0.0    0.0   0
91    0    0   0.0   NaN    0.0   39.6    2.9   0
92    0    0  21.0  21.0    1.3  118.7   99.9   0
93    0    0   0.0   NaN    0.0   39.6    0.0   0
94    0    0  21.0  21.0    1.3  118.7   11.8   0
95    1    0  50.0  50.0    3.1  158.3  100.0   0
96    0    0   8.0   8.0    0.5  100.0   81.2   0
97    1    0   8.0   8.0    0.5  139.6    NaN   0
98    1    0  28.0  28.0    2.3  158.3  100.0   0
99    0    0   0.0   NaN    0.0   39.6    NaN   0
100   1    0   3.0   3.0    0.2  118.7  100.0   0
101   0    0  15.0  15.0    1.3  118.7    NaN   0
102   0    0  12.0  12.0    1.0  116.7    NaN   0
103   0    0   7.0   7.0    0.4   95.8    NaN   0
104   0    0   0.0   NaN    0.0   39.6   10.1   0
105   1    0  52.0  52.0    7.4  158.3   99.7   0

[106 rows x 19 columns]

In [5]:
# This makes things pretty
df

,Rk,Player,Tm,Age,Pos,G,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sk
0,1,Ben Roethlisberger,PIT,36,QB,16,16,452,675,67.0,5129,34,16,7.6,11.3,320.6,96.5,71.0,24
1,2,Andrew Luck,IND,29,QB,16,16,430,639,67.3,4593,39,15,7.2,10.7,287.1,98.7,69.4,18
2,3,Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42
3,4,Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40
4,5,Aaron Rodgers,GNB,35,QB,16,16,372,597,62.3,4442,25,2,7.4,11.9,277.6,97.6,54.4,49
5,6,Case Keenum,DEN,30,QB,16,16,365,586,62.3,3890,18,15,6.6,10.7,243.1,81.2,45.5,34
6,7,Patrick Mahomes,KAN,23,QB,16,16,383,580,66.0,5097,50,12,8.8,13.3,318.6,113.8,80.4,26
7,8,Eli Manning,NYG,37,QB,16,16,380,576,66.0,4299,21,11,7.5,11.3,268.7,92.4,48.7,47
8,9,Tom Brady,NWE,41,QB,16,16,375,570,65.8,4355,29,11,7.6,11.6,272.2,97.7,66.6,21
9,10,Jared Goff,LAR,24,QB,16,16,364,561,64.9,4688,32,12,8.4,12.9,293.0,101.1,63.1,33
10,11,Matthew Stafford,DET,30,QB,16,16,367,555,66.1,3777,21,11,6.8,10.3,236.1,89.9,48.4,40
11,12,Derek Carr,OAK,27,QB,16,16,381,553,68.9,4049,19,10,7.3,10.6,253.1,93.9,46.9,51
12,13,Dak Prescott,DAL,25,QB,16,16,356,526,67.7,3885,22,8,7.4,10.9,242.8,96.9,56.2,56
13,14,Philip Rivers,LAC,37,QB,16,16,347,508,68.3,4308,32,12,8.5,12.4,269.3,105.5,69.1,32
14,15,Deshaun Watson,HOU,23,QB,16,16,345,505,68.3,4165,26,9,8.2,12.1,260.3,103.1,60.7,62
15,16,Drew Brees,NOR,39,QB,15,15,364,489,74.4,3992,32,5,8.2,11.0,266.1,115.7,80.4,17
16,17,Baker Mayfield,CLE,23,QB,14,13,310,486,63.8,3725,27,14,7.7,12.0,266.1,93.7,53.2,25
17,18,Cam Newton,CAR,29,QB,14,14,320,471,67.9,3395,24,13,7.2,10.6,242.5,94.2,55.0,29
18,19,Mitchell Trubisky,CHI,24,QB,14,14,289,434,66.6,3223,24,12,7.4,11.2,230.2,95.4,70.8,24
19,20,Russell Wilson,SEA,30,QB,16,16,280,427,65.6,3448,35,7,8.1,12.3,215.5,110.9,62.8,51
20,21,Sam Darnold,NYJ,21,QB,13,13,239,414,57.7,2865,17,15,6.9,12.0,220.4,77.6,45.5,30
21,22,Blake Bortles,JAX,26,QB,13,12,243,403,60.3,2718,13,11,6.7,11.2,209.1,79.8,41.7,31
22,23,Carson Wentz,PHI,26,QB,11,11,279,401,69.6,3074,21,7,7.7,11.0,279.5,102.2,62.6,31
23,24,Josh Rosen,ARI,21,QB,14,13,217,393,55.2,2278,11,14,5.8,10.5,162.7,66.7,24.7,45
24,25,Joe Flacco,BAL,33,QB,9,9,232,379,61.2,2465,12,6,6.5,10.6,273.9,84.2,56.3,16
25,26,Jameis Winston,TAM,24,QB,11,9,244,378,64.6,2992,19,14,7.9,12.3,272.0,90.2,69.7,27
26,27,Andy Dalton,CIN,31,QB,11,11,226,365,61.9,2566,21,11,7.0,11.4,233.3,89.6,62.3,21
27,28,Marcus Mariota,TEN,25,QB,14,13,228,331,68.9,2528,11,8,7.6,11.1,180.6,92.3,50.6,42
28,29,Alex Smith,WAS,34,QB,10,10,205,328,62.5,2180,10,5,6.6,10.6,218.0,85.7,51.4,22
29,30,Josh Allen,BUF,22,QB,12,11,169,320,52.8,2074,10,12,6.5,12.3,172.8,67.9,49.8,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,77,Nelson Agholor,PHI,25,WR,16,16,1,1,100.0,15,0,0,15.0,15.0,0.9,118.7,100.0,0
77,78,Danny Amendola,MIA,33,WR,15,15,1,1,100.0,28,1,0,28.0,28.0,1.9,158.3,100.0,0
78,79,Bryan Anger,TAM,30,P,16,0,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,NaN,0
79,80,Cole Beasley,DAL,29,wr,16,4,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,27.6,0
80,81,Corey Bojorquez,BUF,22,P,8,0,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,NaN,0
81,82,Chris Boswell,PIT,27,K,15,0,1,1,100.0,2,1,0,2.0,2.0,0.1,118.7,NaN,0
82,83,Tyler Boyd,CIN,24,WR,14,14,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,2.8,0
83,84,Antonio Brown,PIT,30,WR,15,15,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,2.8,0
84,85,Kevin Byard,TEN,25,FS,16,16,1,1,100.0,66,1,0,66.0,66.0,4.1,158.3,NaN,0
85,86,Tarik Cohen,CHI,23,rb/wr,16,7,1,1,100.0,1,1,0,1.0,1.0,0.1,118.7,100.0,0
86,87,Logan Cooke,JAX,23,P,16,0,1,1,100.0,4,0,0,4.0,4.0,0.3,83.3,NaN,0
87,88,Eric Ebron,IND,25,te/wr,16,8,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,0.0,0
88,89,Bruce Ellington,2TM,27,NaN,7,3,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,NaN,0
89,90,Larry Fitzgerald,ARI,35,WR,16,16,1,1,100.0,32,1,0,32.0,32.0,2.0,158.3,100.0,0
90,91,Dontrell Hilliard,CLE,23,NaN,11,0,0,1,0.0,0,0,1,0.0,NaN,0.0,0.0,0.0,0
91,92,DeAndre Hopkins,HOU,26,WR,16,16,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,2.9,0
92,93,Darius Jennings,TEN,26,NaN,16,0,1,1,100.0,21,0,0,21.0,21.0,1.3,118.7,99.9,0
93,94,Zay Jones,BUF,23,WR,16,15,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,0.0,0
94,95,Sam Koch,BAL,36,P,16,0,1,1,100.0,21,0,0,21.0,21.0,1.3,118.7,11.8,0
95,96,Christian McCaffrey,CAR,22,RB,16,16,1,1,100.0,50,1,0,50.0,50.0,3.1,158.3,100.0,0
96,97,Anthony Miller,CHI,24,wr,15,4,1,1,100.0,8,0,0,8.0,8.0,0.5,100.0,81.2,0
97,98,Matt Prater,DET,34,K,16,0,1,1,100.0,8,1,0,8.0,8.0,0.5,139.6,NaN,0
98,99,Emmanuel Sanders,DEN,31,WR,12,12,1,1,100.0,28,1,0,28.0,28.0,2.3,158.3,100.0,0
99,100,JK Scott,GNB,22,P,16,0,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,NaN,0
100,101,Kenny Stills,MIA,26,WR,15,15,1,1,100.0,3,1,0,3.0,3.0,0.2,118.7,100.0,0
101,102,Logan Thomas,BUF,27,te,12,3,1,1,100.0,15,0,0,15.0,15.0,1.3,118.7,NaN,0
102,103,Colby Wadman,DEN,23,P,12,0,1,1,100.0,12,0,0,12.0,12.0,1.0,116.7,NaN,0
103,104,Tress Way,WAS,28,P,16,0,1,1,100.0,7,0,0,7.0,7.0,0.4,95.8,NaN,0
104,105,Dede Westbrook,JAX,25,WR,16,9,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,10.1,0
105,106,Albert Wilson,MIA,26,wr,7,3,1,1,100.0,52,1,0,52.0,52.0,7.4,158.3,99.7,0

In [6]:
# Print out the head(start) of your DataFrame
df.head()

,Rk,Player,Tm,Age,Pos,G,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sk
0,1,Ben Roethlisberger,PIT,36,QB,16,16,452,675,67.0,5129,34,16,7.6,11.3,320.6,96.5,71.0,24
1,2,Andrew Luck,IND,29,QB,16,16,430,639,67.3,4593,39,15,7.2,10.7,287.1,98.7,69.4,18
2,3,Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42
3,4,Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40
4,5,Aaron Rodgers,GNB,35,QB,16,16,372,597,62.3,4442,25,2,7.4,11.9,277.6,97.6,54.4,49

In [7]:
# Print out the tail(end) of your DataFrame
df.tail()

,Rk,Player,Tm,Age,Pos,G,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sk
101,102,Logan Thomas,BUF,27,te,12,3,1,1,100.0,15,0,0,15.0,15.0,1.3,118.7,NaN,0
102,103,Colby Wadman,DEN,23,P,12,0,1,1,100.0,12,0,0,12.0,12.0,1.0,116.7,NaN,0
103,104,Tress Way,WAS,28,P,16,0,1,1,100.0,7,0,0,7.0,7.0,0.4,95.8,NaN,0
104,105,Dede Westbrook,JAX,25,WR,16,9,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,10.1,0
105,106,Albert Wilson,MIA,26,wr,7,3,1,1,100.0,52,1,0,52.0,52.0,7.4,158.3,99.7,0

In [8]:
# Print out n number of rows
num_rows = 10
df.head(num_rows)

,Rk,Player,Tm,Age,Pos,G,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sk
0,1,Ben Roethlisberger,PIT,36,QB,16,16,452,675,67.0,5129,34,16,7.6,11.3,320.6,96.5,71.0,24
1,2,Andrew Luck,IND,29,QB,16,16,430,639,67.3,4593,39,15,7.2,10.7,287.1,98.7,69.4,18
2,3,Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42
3,4,Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40
4,5,Aaron Rodgers,GNB,35,QB,16,16,372,597,62.3,4442,25,2,7.4,11.9,277.6,97.6,54.4,49
5,6,Case Keenum,DEN,30,QB,16,16,365,586,62.3,3890,18,15,6.6,10.7,243.1,81.2,45.5,34
6,7,Patrick Mahomes,KAN,23,QB,16,16,383,580,66.0,5097,50,12,8.8,13.3,318.6,113.8,80.4,26
7,8,Eli Manning,NYG,37,QB,16,16,380,576,66.0,4299,21,11,7.5,11.3,268.7,92.4,48.7,47
8,9,Tom Brady,NWE,41,QB,16,16,375,570,65.8,4355,29,11,7.6,11.6,272.2,97.7,66.6,21
9,10,Jared Goff,LAR,24,QB,16,16,364,561,64.9,4688,32,12,8.4,12.9,293.0,101.1,63.1,33

In [9]:
# Get dimensions of dataframe in the format of (rows, columns)
df.shape

(106, 19)

In [10]:
# Get the names of of the columns
df.columns

Index(['Rk', 'Player', 'Tm', 'Age', 'Pos', 'G', 'GS', 'Cmp', 'Att', 'Cmp%',
       'Yds', 'TD', 'Int', 'Y/A', 'Y/C', 'Y/G', 'Rate', 'QBR', 'Sk'],
      dtype='object')

In [11]:
# Get the tyeps of each column
df.dtypes

Rk          int64
Player     object
Tm         object
Age         int64
Pos        object
G           int64
GS          int64
Cmp         int64
Att         int64
Cmp%      float64
Yds         int64
TD          int64
Int         int64
Y/A       float64
Y/C       float64
Y/G       float64
Rate      float64
QBR       float64
Sk          int64
dtype: object

In [12]:
# Pick out specifc columns that your want
new_df = df[["Player"]]
new_df.head()

               Player
0  Ben Roethlisberger
1         Andrew Luck
2           Matt Ryan
3        Kirk Cousins
4       Aaron Rodgers

In [13]:
# Get more than one column
new_df = df[["Player", "Tm", "TD", "Yds"]]
new_df.head()

               Player   Tm  TD   Yds
0  Ben Roethlisberger  PIT  34  5129
1         Andrew Luck  IND  39  4593
2           Matt Ryan  ATL  35  4924
3        Kirk Cousins  MIN  30  4298
4       Aaron Rodgers  GNB  25  4442

In [14]:
# Get the name of the columns
column_names = df.columns
column_names

Index(['Rk', 'Player', 'Tm', 'Age', 'Pos', 'G', 'GS', 'Cmp', 'Att', 'Cmp%',
       'Yds', 'TD', 'Int', 'Y/A', 'Y/C', 'Y/G', 'Rate', 'QBR', 'Sk'],
      dtype='object')

In [15]:
column_names[2]

'Tm'

In [16]:
# Change the column_names!!!
list_cols = column_names.to_list()
list_cols[2] = "Team"
df.columns = list_cols
df.head()

,Rk,Player,Team,Age,Pos,G,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sk
0,1,Ben Roethlisberger,PIT,36,QB,16,16,452,675,67.0,5129,34,16,7.6,11.3,320.6,96.5,71.0,24
1,2,Andrew Luck,IND,29,QB,16,16,430,639,67.3,4593,39,15,7.2,10.7,287.1,98.7,69.4,18
2,3,Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42
3,4,Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40
4,5,Aaron Rodgers,GNB,35,QB,16,16,372,597,62.3,4442,25,2,7.4,11.9,277.6,97.6,54.4,49

In [17]:
# Change the column names the proper way!
df.rename(columns = {
    "Tm" : "Team",
    "G" : "Games",
    "Sk" : "Sacks"
}, inplace = True)

df.head()

,Rk,Player,Team,Age,Pos,Games,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sacks
0,1,Ben Roethlisberger,PIT,36,QB,16,16,452,675,67.0,5129,34,16,7.6,11.3,320.6,96.5,71.0,24
1,2,Andrew Luck,IND,29,QB,16,16,430,639,67.3,4593,39,15,7.2,10.7,287.1,98.7,69.4,18
2,3,Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42
3,4,Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40
4,5,Aaron Rodgers,GNB,35,QB,16,16,372,597,62.3,4442,25,2,7.4,11.9,277.6,97.6,54.4,49

In [18]:
df = df.drop(columns=["Rk"])
df.head()

,Player,Team,Age,Pos,Games,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sacks
0,Ben Roethlisberger,PIT,36,QB,16,16,452,675,67.0,5129,34,16,7.6,11.3,320.6,96.5,71.0,24
1,Andrew Luck,IND,29,QB,16,16,430,639,67.3,4593,39,15,7.2,10.7,287.1,98.7,69.4,18
2,Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42
3,Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40
4,Aaron Rodgers,GNB,35,QB,16,16,372,597,62.3,4442,25,2,7.4,11.9,277.6,97.6,54.4,49

In [19]:
# Add a new column
df["New Col"] = df["Cmp"]
df.head()

,Player,Team,Age,Pos,Games,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sacks,New Col
0,Ben Roethlisberger,PIT,36,QB,16,16,452,675,67.0,5129,34,16,7.6,11.3,320.6,96.5,71.0,24,452
1,Andrew Luck,IND,29,QB,16,16,430,639,67.3,4593,39,15,7.2,10.7,287.1,98.7,69.4,18,430
2,Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42,422
3,Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40,425
4,Aaron Rodgers,GNB,35,QB,16,16,372,597,62.3,4442,25,2,7.4,11.9,277.6,97.6,54.4,49,372

In [20]:
df = df.drop(columns=["New Col"])

In [21]:
df["TD_Ratio"] = round(df["TD"] / df["Int"], 2)
df

,Player,Team,Age,Pos,Games,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sacks,TD_Ratio
0,Ben Roethlisberger,PIT,36,QB,16,16,452,675,67.0,5129,34,16,7.6,11.3,320.6,96.5,71.0,24,2.12
1,Andrew Luck,IND,29,QB,16,16,430,639,67.3,4593,39,15,7.2,10.7,287.1,98.7,69.4,18,2.60
2,Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42,5.00
3,Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40,3.00
4,Aaron Rodgers,GNB,35,QB,16,16,372,597,62.3,4442,25,2,7.4,11.9,277.6,97.6,54.4,49,12.50
5,Case Keenum,DEN,30,QB,16,16,365,586,62.3,3890,18,15,6.6,10.7,243.1,81.2,45.5,34,1.20
6,Patrick Mahomes,KAN,23,QB,16,16,383,580,66.0,5097,50,12,8.8,13.3,318.6,113.8,80.4,26,4.17
7,Eli Manning,NYG,37,QB,16,16,380,576,66.0,4299,21,11,7.5,11.3,268.7,92.4,48.7,47,1.91
8,Tom Brady,NWE,41,QB,16,16,375,570,65.8,4355,29,11,7.6,11.6,272.2,97.7,66.6,21,2.64
9,Jared Goff,LAR,24,QB,16,16,364,561,64.9,4688,32,12,8.4,12.9,293.0,101.1,63.1,33,2.67
10,Matthew Stafford,DET,30,QB,16,16,367,555,66.1,3777,21,11,6.8,10.3,236.1,89.9,48.4,40,1.91
11,Derek Carr,OAK,27,QB,16,16,381,553,68.9,4049,19,10,7.3,10.6,253.1,93.9,46.9,51,1.90
12,Dak Prescott,DAL,25,QB,16,16,356,526,67.7,3885,22,8,7.4,10.9,242.8,96.9,56.2,56,2.75
13,Philip Rivers,LAC,37,QB,16,16,347,508,68.3,4308,32,12,8.5,12.4,269.3,105.5,69.1,32,2.67
14,Deshaun Watson,HOU,23,QB,16,16,345,505,68.3,4165,26,9,8.2,12.1,260.3,103.1,60.7,62,2.89
15,Drew Brees,NOR,39,QB,15,15,364,489,74.4,3992,32,5,8.2,11.0,266.1,115.7,80.4,17,6.40
16,Baker Mayfield,CLE,23,QB,14,13,310,486,63.8,3725,27,14,7.7,12.0,266.1,93.7,53.2,25,1.93
17,Cam Newton,CAR,29,QB,14,14,320,471,67.9,3395,24,13,7.2,10.6,242.5,94.2,55.0,29,1.85
18,Mitchell Trubisky,CHI,24,QB,14,14,289,434,66.6,3223,24,12,7.4,11.2,230.2,95.4,70.8,24,2.00
19,Russell Wilson,SEA,30,QB,16,16,280,427,65.6,3448,35,7,8.1,12.3,215.5,110.9,62.8,51,5.00
20,Sam Darnold,NYJ,21,QB,13,13,239,414,57.7,2865,17,15,6.9,12.0,220.4,77.6,45.5,30,1.13
21,Blake Bortles,JAX,26,QB,13,12,243,403,60.3,2718,13,11,6.7,11.2,209.1,79.8,41.7,31,1.18
22,Carson Wentz,PHI,26,QB,11,11,279,401,69.6,3074,21,7,7.7,11.0,279.5,102.2,62.6,31,3.00
23,Josh Rosen,ARI,21,QB,14,13,217,393,55.2,2278,11,14,5.8,10.5,162.7,66.7,24.7,45,0.79
24,Joe Flacco,BAL,33,QB,9,9,232,379,61.2,2465,12,6,6.5,10.6,273.9,84.2,56.3,16,2.00
25,Jameis Winston,TAM,24,QB,11,9,244,378,64.6,2992,19,14,7.9,12.3,272.0,90.2,69.7,27,1.36
26,Andy Dalton,CIN,31,QB,11,11,226,365,61.9,2566,21,11,7.0,11.4,233.3,89.6,62.3,21,1.91
27,Marcus Mariota,TEN,25,QB,14,13,228,331,68.9,2528,11,8,7.6,11.1,180.6,92.3,50.6,42,1.38
28,Alex Smith,WAS,34,QB,10,10,205,328,62.5,2180,10,5,6.6,10.6,218.0,85.7,51.4,22,2.00
29,Josh Allen,BUF,22,QB,12,11,169,320,52.8,2074,10,12,6.5,12.3,172.8,67.9,49.8,28,0.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,Nelson Agholor,PHI,25,WR,16,16,1,1,100.0,15,0,0,15.0,15.0,0.9,118.7,100.0,0,NaN
77,Danny Amendola,MIA,33,WR,15,15,1,1,100.0,28,1,0,28.0,28.0,1.9,158.3,100.0,0,inf
78,Bryan Anger,TAM,30,P,16,0,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,NaN,0,NaN
79,Cole Beasley,DAL,29,wr,16,4,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,27.6,0,NaN
80,Corey Bojorquez,BUF,22,P,8,0,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,NaN,0,NaN
81,Chris Boswell,PIT,27,K,15,0,1,1,100.0,2,1,0,2.0,2.0,0.1,118.7,NaN,0,inf
82,Tyler Boyd,CIN,24,WR,14,14,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,2.8,0,NaN
83,Antonio Brown,PIT,30,WR,15,15,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,2.8,0,NaN
84,Kevin Byard,TEN,25,FS,16,16,1,1,100.0,66,1,0,66.0,66.0,4.1,158.3,NaN,0,inf
85,Tarik Cohen,CHI,23,rb/wr,16,7,1,1,100.0,1,1,0,1.0,1.0,0.1,118.7,100.0,0,inf
86,Logan Cooke,JAX,23,P,16,0,1,1,100.0,4,0,0,4.0,4.0,0.3,83.3,NaN,0,NaN
87,Eric Ebron,IND,25,te/wr,16,8,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,0.0,0,NaN
88,Bruce Ellington,2TM,27,NaN,7,3,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,NaN,0,NaN
89,Larry Fitzgerald,ARI,35,WR,16,16,1,1,100.0,32,1,0,32.0,32.0,2.0,158.3,100.0,0,inf
90,Dontrell Hilliard,CLE,23,NaN,11,0,0,1,0.0,0,0,1,0.0,NaN,0.0,0.0,0.0,0,0.00
91,DeAndre Hopkins,HOU,26,WR,16,16,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,2.9,0,NaN
92,Darius Jennings,TEN,26,NaN,16,0,1,1,100.0,21,0,0,21.0,21.0,1.3,118.7,99.9,0,NaN
93,Zay Jones,BUF,23,WR,16,15,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,0.0,0,NaN
94,Sam Koch,BAL,36,P,16,0,1,1,100.0,21,0,0,21.0,21.0,1.3,118.7,11.8,0,NaN
95,Christian McCaffrey,CAR,22,RB,16,16,1,1,100.0,50,1,0,50.0,50.0,3.1,158.3,100.0,0,inf
96,Anthony Miller,CHI,24,wr,15,4,1,1,100.0,8,0,0,8.0,8.0,0.5,100.0,81.2,0,NaN
97,Matt Prater,DET,34,K,16,0,1,1,100.0,8,1,0,8.0,8.0,0.5,139.6,NaN,0,inf
98,Emmanuel Sanders,DEN,31,WR,12,12,1,1,100.0,28,1,0,28.0,28.0,2.3,158.3,100.0,0,inf
99,JK Scott,GNB,22,P,16,0,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,NaN,0,NaN
100,Kenny Stills,MIA,26,WR,15,15,1,1,100.0,3,1,0,3.0,3.0,0.2,118.7,100.0,0,inf
101,Logan Thomas,BUF,27,te,12,3,1,1,100.0,15,0,0,15.0,15.0,1.3,118.7,NaN,0,NaN
102,Colby Wadman,DEN,23,P,12,0,1,1,100.0,12,0,0,12.0,12.0,1.0,116.7,NaN,0,NaN
103,Tress Way,WAS,28,P,16,0,1,1,100.0,7,0,0,7.0,7.0,0.4,95.8,NaN,0,NaN
104,Dede Westbrook,JAX,25,WR,16,9,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,10.1,0,NaN
105,Albert Wilson,MIA,26,wr,7,3,1,1,100.0,52,1,0,52.0,52.0,7.4,158.3,99.7,0,inf

In [22]:
# Select a single row
df.iloc[0]
# This is bad!!!

Player      Ben Roethlisberger
Team                       PIT
Age                         36
Pos                         QB
Games                       16
GS                          16
Cmp                        452
Att                        675
Cmp%                        67
Yds                       5129
TD                          34
Int                         16
Y/A                        7.6
Y/C                       11.3
Y/G                      320.6
Rate                      96.5
QBR                         71
Sacks                       24
TD_Ratio                  2.12
Name: 0, dtype: object

In [23]:
# This is good :)
# Why?? iloc expects a range
df.iloc[[0]]

,Player,Team,Age,Pos,Games,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sacks,TD_Ratio
0,Ben Roethlisberger,PIT,36,QB,16,16,452,675,67.0,5129,34,16,7.6,11.3,320.6,96.5,71.0,24,2.12

In [24]:
df.iloc[3:10]

,Player,Team,Age,Pos,Games,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sacks,TD_Ratio
3,Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40,3.00
4,Aaron Rodgers,GNB,35,QB,16,16,372,597,62.3,4442,25,2,7.4,11.9,277.6,97.6,54.4,49,12.50
5,Case Keenum,DEN,30,QB,16,16,365,586,62.3,3890,18,15,6.6,10.7,243.1,81.2,45.5,34,1.20
6,Patrick Mahomes,KAN,23,QB,16,16,383,580,66.0,5097,50,12,8.8,13.3,318.6,113.8,80.4,26,4.17
7,Eli Manning,NYG,37,QB,16,16,380,576,66.0,4299,21,11,7.5,11.3,268.7,92.4,48.7,47,1.91
8,Tom Brady,NWE,41,QB,16,16,375,570,65.8,4355,29,11,7.6,11.6,272.2,97.7,66.6,21,2.64
9,Jared Goff,LAR,24,QB,16,16,364,561,64.9,4688,32,12,8.4,12.9,293.0,101.1,63.1,33,2.67

In [25]:
# Reset the index column
df = df.set_index("Player")
df.head()

,Team,Age,Pos,Games,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sacks,TD_Ratio
Player,,,,,,,,,,,,,,,,,,
Ben Roethlisberger,PIT,36,QB,16,16,452,675,67.0,5129,34,16,7.6,11.3,320.6,96.5,71.0,24,2.12
Andrew Luck,IND,29,QB,16,16,430,639,67.3,4593,39,15,7.2,10.7,287.1,98.7,69.4,18,2.60
Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42,5.00
Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40,3.00
Aaron Rodgers,GNB,35,QB,16,16,372,597,62.3,4442,25,2,7.4,11.9,277.6,97.6,54.4,49,12.50

In [26]:
df.loc[["Matthew Stafford"]]

,Team,Age,Pos,Games,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sacks,TD_Ratio
Player,,,,,,,,,,,,,,,,,,
Matthew Stafford,DET,30,QB,16,16,367,555,66.1,3777,21,11,6.8,10.3,236.1,89.9,48.4,40,1.91

In [27]:
qbs = df[df["Pos"] == "QB"]
qbs.head()

,Team,Age,Pos,Games,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sacks,TD_Ratio
Player,,,,,,,,,,,,,,,,,,
Ben Roethlisberger,PIT,36,QB,16,16,452,675,67.0,5129,34,16,7.6,11.3,320.6,96.5,71.0,24,2.12
Andrew Luck,IND,29,QB,16,16,430,639,67.3,4593,39,15,7.2,10.7,287.1,98.7,69.4,18,2.60
Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42,5.00
Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40,3.00
Aaron Rodgers,GNB,35,QB,16,16,372,597,62.3,4442,25,2,7.4,11.9,277.6,97.6,54.4,49,12.50

In [28]:
qbs.shape

(32, 18)

In [29]:
all_qbs = df[(df["Pos"] == "QB") | (df["Pos"] == "qb")]
all_qbs.head()

,Team,Age,Pos,Games,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sacks,TD_Ratio
Player,,,,,,,,,,,,,,,,,,
Ben Roethlisberger,PIT,36,QB,16,16,452,675,67.0,5129,34,16,7.6,11.3,320.6,96.5,71.0,24,2.12
Andrew Luck,IND,29,QB,16,16,430,639,67.3,4593,39,15,7.2,10.7,287.1,98.7,69.4,18,2.60
Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42,5.00
Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40,3.00
Aaron Rodgers,GNB,35,QB,16,16,372,597,62.3,4442,25,2,7.4,11.9,277.6,97.6,54.4,49,12.50

In [30]:
all_qbs.shape

(54, 18)

In [31]:
starters = df[(df["Pos"] == "QB") & (df["GS"] == 16)]
starters

,Team,Age,Pos,Games,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sacks,TD_Ratio
Player,,,,,,,,,,,,,,,,,,
Ben Roethlisberger,PIT,36,QB,16,16,452,675,67.0,5129,34,16,7.6,11.3,320.6,96.5,71.0,24,2.12
Andrew Luck,IND,29,QB,16,16,430,639,67.3,4593,39,15,7.2,10.7,287.1,98.7,69.4,18,2.60
Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42,5.00
Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40,3.00
Aaron Rodgers,GNB,35,QB,16,16,372,597,62.3,4442,25,2,7.4,11.9,277.6,97.6,54.4,49,12.50
Case Keenum,DEN,30,QB,16,16,365,586,62.3,3890,18,15,6.6,10.7,243.1,81.2,45.5,34,1.20
Patrick Mahomes,KAN,23,QB,16,16,383,580,66.0,5097,50,12,8.8,13.3,318.6,113.8,80.4,26,4.17
Eli Manning,NYG,37,QB,16,16,380,576,66.0,4299,21,11,7.5,11.3,268.7,92.4,48.7,47,1.91
Tom Brady,NWE,41,QB,16,16,375,570,65.8,4355,29,11,7.6,11.6,272.2,97.7,66.6,21,2.64
Jared Goff,LAR,24,QB,16,16,364,561,64.9,4688,32,12,8.4,12.9,293.0,101.1,63.1,33,2.67
Matthew Stafford,DET,30,QB,16,16,367,555,66.1,3777,21,11,6.8,10.3,236.1,89.9,48.4,40,1.91
Derek Carr,OAK,27,QB,16,16,381,553,68.9,4049,19,10,7.3,10.6,253.1,93.9,46.9,51,1.90
Dak Prescott,DAL,25,QB,16,16,356,526,67.7,3885,22,8,7.4,10.9,242.8,96.9,56.2,56,2.75
Philip Rivers,LAC,37,QB,16,16,347,508,68.3,4308,32,12,8.5,12.4,269.3,105.5,69.1,32,2.67
Deshaun Watson,HOU,23,QB,16,16,345,505,68.3,4165,26,9,8.2,12.1,260.3,103.1,60.7,62,2.89
Russell Wilson,SEA,30,QB,16,16,280,427,65.6,3448,35,7,8.1,12.3,215.5,110.9,62.8,51,5.00

In [32]:
# Filter on list condition
NFC_South = ["NOR", "ATL", "TAM", "CAR"]
nfc_south_qbs = all_qbs[all_qbs["Team"].isin(NFC_South)]
nfc_south_qbs

,Team,Age,Pos,Games,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sacks,TD_Ratio
Player,,,,,,,,,,,,,,,,,,
Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42,5.00
Drew Brees,NOR,39,QB,15,15,364,489,74.4,3992,32,5,8.2,11.0,266.1,115.7,80.4,17,6.40
Cam Newton,CAR,29,QB,14,14,320,471,67.9,3395,24,13,7.2,10.6,242.5,94.2,55.0,29,1.85
Jameis Winston,TAM,24,QB,11,9,244,378,64.6,2992,19,14,7.9,12.3,272.0,90.2,69.7,27,1.36
Ryan Fitzpatrick,TAM,36,qb,8,7,164,246,66.7,2366,17,12,9.6,14.4,295.8,100.4,62.1,14,1.42
Taylor Heinicke,CAR,25,qb,6,1,35,57,61.4,320,1,3,5.6,9.1,53.3,60.6,24.6,2,0.33
Kyle Allen,CAR,22,qb,2,1,20,31,64.5,266,2,0,8.6,13.3,133.0,113.1,96.4,0,inf
Teddy Bridgewater,NOR,26,qb,5,1,14,23,60.9,118,1,1,5.1,8.4,23.6,70.6,39.8,2,1.00

In [33]:
# Sort the values least to greatest
eligible = all_qbs[all_qbs["Games"] > 6]
eligible = eligible.sort_values("Cmp%", ascending=False)
eligible.head()

,Team,Age,Pos,Games,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sacks,TD_Ratio
Player,,,,,,,,,,,,,,,,,,
Drew Brees,NOR,39,QB,15,15,364,489,74.4,3992,32,5,8.2,11.0,266.1,115.7,80.4,17,6.40
Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40,3.00
Carson Wentz,PHI,26,QB,11,11,279,401,69.6,3074,21,7,7.7,11.0,279.5,102.2,62.6,31,3.00
Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42,5.00
Marcus Mariota,TEN,25,QB,14,13,228,331,68.9,2528,11,8,7.6,11.1,180.6,92.3,50.6,42,1.38