In [5]:
import pandas as pd

In [77]:
# Read in the dataframe and print it
passing_stats = pd.read_excel("nfl_stats.xlsx")
passing_stats

,Rk,Player,Tm,Age,Pos,G,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sk
0,1,Ben Roethlisberger,PIT,36,QB,16,16,452,675,67.0,5129,34,16,7.6,11.3,320.6,96.5,71.0,24
1,2,Andrew Luck*,IND,29,QB,16,16,430,639,67.3,4593,39,15,7.2,10.7,287.1,98.7,69.4,18
2,3,Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42
3,4,Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40
4,5,Aaron Rodgers*,GNB,35,QB,16,16,372,597,62.3,4442,25,2,7.4,11.9,277.6,97.6,54.4,49
5,6,Case Keenum,DEN,30,QB,16,16,365,586,62.3,3890,18,15,6.6,10.7,243.1,81.2,45.5,34
6,7,Patrick Mahomes*+,KAN,23,QB,16,16,383,580,66.0,5097,50,12,8.8,13.3,318.6,113.8,80.4,26
7,8,Eli Manning,NYG,37,QB,16,16,380,576,66.0,4299,21,11,7.5,11.3,268.7,92.4,48.7,47
8,9,Tom Brady*,NWE,41,QB,16,16,375,570,65.8,4355,29,11,7.6,11.6,272.2,97.7,66.6,21
9,10,Jared Goff*,LAR,24,QB,16,16,364,561,64.9,4688,32,12,8.4,12.9,293.0,101.1,63.1,33
10,11,Matthew Stafford,DET,30,QB,16,16,367,555,66.1,3777,21,11,6.8,10.3,236.1,89.9,48.4,40
11,12,Derek Carr,OAK,27,QB,16,16,381,553,68.9,4049,19,10,7.3,10.6,253.1,93.9,46.9,51
12,13,Dak Prescott*,DAL,25,QB,16,16,356,526,67.7,3885,22,8,7.4,10.9,242.8,96.9,56.2,56
13,14,Philip Rivers*,LAC,37,QB,16,16,347,508,68.3,4308,32,12,8.5,12.4,269.3,105.5,69.1,32
14,15,Deshaun Watson*,HOU,23,QB,16,16,345,505,68.3,4165,26,9,8.2,12.1,260.3,103.1,60.7,62
15,16,Drew Brees*,NOR,39,QB,15,15,364,489,74.4,3992,32,5,8.2,11.0,266.1,115.7,80.4,17
16,17,Baker Mayfield,CLE,23,QB,14,13,310,486,63.8,3725,27,14,7.7,12.0,266.1,93.7,53.2,25
17,18,Cam Newton,CAR,29,QB,14,14,320,471,67.9,3395,24,13,7.2,10.6,242.5,94.2,55.0,29
18,19,Mitchell Trubisky*,CHI,24,QB,14,14,289,434,66.6,3223,24,12,7.4,11.2,230.2,95.4,70.8,24
19,20,Russell Wilson*,SEA,30,QB,16,16,280,427,65.6,3448,35,7,8.1,12.3,215.5,110.9,62.8,51
20,21,Sam Darnold,NYJ,21,QB,13,13,239,414,57.7,2865,17,15,6.9,12.0,220.4,77.6,45.5,30
21,22,Blake Bortles,JAX,26,QB,13,12,243,403,60.3,2718,13,11,6.7,11.2,209.1,79.8,41.7,31
22,23,Carson Wentz,PHI,26,QB,11,11,279,401,69.6,3074,21,7,7.7,11.0,279.5,102.2,62.6,31
23,24,Josh Rosen,ARI,21,QB,14,13,217,393,55.2,2278,11,14,5.8,10.5,162.7,66.7,24.7,45
24,25,Joe Flacco,BAL,33,QB,9,9,232,379,61.2,2465,12,6,6.5,10.6,273.9,84.2,56.3,16
25,26,Jameis Winston,TAM,24,QB,11,9,244,378,64.6,2992,19,14,7.9,12.3,272.0,90.2,69.7,27
26,27,Andy Dalton,CIN,31,QB,11,11,226,365,61.9,2566,21,11,7.0,11.4,233.3,89.6,62.3,21
27,28,Marcus Mariota,TEN,25,QB,14,13,228,331,68.9,2528,11,8,7.6,11.1,180.6,92.3,50.6,42
28,29,Alex Smith,WAS,34,QB,10,10,205,328,62.5,2180,10,5,6.6,10.6,218.0,85.7,51.4,22
29,30,Josh Allen,BUF,22,QB,12,11,169,320,52.8,2074,10,12,6.5,12.3,172.8,67.9,49.8,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,77,Nelson Agholor,PHI,25,WR,16,16,1,1,100.0,15,0,0,15.0,15.0,0.9,118.7,100.0,0
77,78,Danny Amendola,MIA,33,WR,15,15,1,1,100.0,28,1,0,28.0,28.0,1.9,158.3,100.0,0
78,79,Bryan Anger,TAM,30,P,16,0,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,NaN,0
79,80,Cole Beasley,DAL,29,wr,16,4,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,27.6,0
80,81,Corey Bojorquez,BUF,22,P,8,0,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,NaN,0
81,82,Chris Boswell,PIT,27,K,15,0,1,1,100.0,2,1,0,2.0,2.0,0.1,118.7,NaN,0
82,83,Tyler Boyd,CIN,24,WR,14,14,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,2.8,0
83,84,Antonio Brown*,PIT,30,WR,15,15,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,2.8,0
84,85,Kevin Byard,TEN,25,FS,16,16,1,1,100.0,66,1,0,66.0,66.0,4.1,158.3,NaN,0
85,86,Tarik Cohen*+,CHI,23,rb/wr,16,7,1,1,100.0,1,1,0,1.0,1.0,0.1,118.7,100.0,0
86,87,Logan Cooke,JAX,23,P,16,0,1,1,100.0,4,0,0,4.0,4.0,0.3,83.3,NaN,0
87,88,Eric Ebron*,IND,25,te/wr,16,8,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,0.0,0
88,89,Bruce Ellington,2TM,27,NaN,7,3,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,NaN,0
89,90,Larry Fitzgerald,ARI,35,WR,16,16,1,1,100.0,32,1,0,32.0,32.0,2.0,158.3,100.0,0
90,91,Dontrell Hilliard,CLE,23,NaN,11,0,0,1,0.0,0,0,1,0.0,NaN,0.0,0.0,0.0,0
91,92,DeAndre Hopkins*+,HOU,26,WR,16,16,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,2.9,0
92,93,Darius Jennings,TEN,26,NaN,16,0,1,1,100.0,21,0,0,21.0,21.0,1.3,118.7,99.9,0
93,94,Zay Jones,BUF,23,WR,16,15,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,0.0,0
94,95,Sam Koch,BAL,36,P,16,0,1,1,100.0,21,0,0,21.0,21.0,1.3,118.7,11.8,0
95,96,Christian McCaffrey,CAR,22,RB,16,16,1,1,100.0,50,1,0,50.0,50.0,3.1,158.3,100.0,0
96,97,Anthony Miller,CHI,24,wr,15,4,1,1,100.0,8,0,0,8.0,8.0,0.5,100.0,81.2,0
97,98,Matt Prater,DET,34,K,16,0,1,1,100.0,8,1,0,8.0,8.0,0.5,139.6,NaN,0
98,99,Emmanuel Sanders,DEN,31,WR,12,12,1,1,100.0,28,1,0,28.0,28.0,2.3,158.3,100.0,0
99,100,JK Scott,GNB,22,P,16,0,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,NaN,0
100,101,Kenny Stills,MIA,26,WR,15,15,1,1,100.0,3,1,0,3.0,3.0,0.2,118.7,100.0,0
101,102,Logan Thomas,BUF,27,te,12,3,1,1,100.0,15,0,0,15.0,15.0,1.3,118.7,NaN,0
102,103,Colby Wadman,DEN,23,P,12,0,1,1,100.0,12,0,0,12.0,12.0,1.0,116.7,NaN,0
103,104,Tress Way,WAS,28,P,16,0,1,1,100.0,7,0,0,7.0,7.0,0.4,95.8,NaN,0
104,105,Dede Westbrook,JAX,25,WR,16,9,0,1,0.0,0,0,0,0.0,NaN,0.0,39.6,10.1,0
105,106,Albert Wilson,MIA,26,wr,7,3,1,1,100.0,52,1,0,52.0,52.0,7.4,158.3,99.7,0

In [86]:
# Create a copy of passing (need to use the copy function in order to create a new dataframe)
best_ratio = passing_stats.copy(deep=True)
# If we do not use the copy function, changing our new table will also change our original (which we don't want!!!)

best_ratio["TD Ratio"] = round(best_ratio["TD"] / best_ratio["Int"], 2)
best_ratio = best_ratio.sort_values("TD Ratio", ascending = False)
best_ratio.head()

,Rk,Player,Tm,Age,Pos,G,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sk,TD Ratio
105,106,Albert Wilson,MIA,26,wr,7,3,1,1,100.0,52,1,0,52.0,52.0,7.4,158.3,99.7,0,inf
74,75,Mohamed Sanu,ATL,29,WR,16,16,1,2,50.0,5,1,0,2.5,5.0,0.3,95.8,32.3,0,inf
84,85,Kevin Byard,TEN,25,FS,16,16,1,1,100.0,66,1,0,66.0,66.0,4.1,158.3,NaN,0,inf
81,82,Chris Boswell,PIT,27,K,15,0,1,1,100.0,2,1,0,2.0,2.0,0.1,118.7,NaN,0,inf
77,78,Danny Amendola,MIA,33,WR,15,15,1,1,100.0,28,1,0,28.0,28.0,1.9,158.3,100.0,0,inf

In [91]:
best_completions = passing_stats.sort_values("Cmp%", ascending = False)
best_completions.head()

,Rk,Player,Tm,Age,Pos,G,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sk
105,106,Albert Wilson,MIA,26,wr,7,3,1,1,100.0,52,1,0,52.0,52.0,7.4,158.3,99.7,0
94,95,Sam Koch,BAL,36,P,16,0,1,1,100.0,21,0,0,21.0,21.0,1.3,118.7,11.8,0
70,71,Odell Beckham,NYG,26,WR,12,12,2,2,100.0,106,2,0,53.0,53.0,8.8,158.3,NaN,0
71,72,Julian Edelman,NWE,32,WR,12,12,2,2,100.0,43,0,0,21.5,21.5,3.6,118.7,94.3,0
76,77,Nelson Agholor,PHI,25,WR,16,16,1,1,100.0,15,0,0,15.0,15.0,0.9,118.7,100.0,0

In [94]:
# fails because NaN values exist
all_qbs = passing_stats[passing_stats["Pos"].str.contains("qb")]

ValueError: cannot index with vector containing NA / NaN values

In [102]:
# Find the rows that have missing values
# Allows you to get a better feel for the types of errors that are ocurring
nan_rows = passing_stats[passing_stats.isnull().any(axis=1)]
nan_rows.head(10)

,Rk,Player,Tm,Age,Pos,G,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sk
50,51,DeShone Kizer,GNB,22,NaN,3,0,20,42,47.6,187,0,2,4.5,9.4,62.3,40.5,25.2,4
55,56,Mike Glennon,ARI,29,NaN,2,0,15,21,71.4,174,1,0,8.3,11.6,87.0,112.0,77.7,1
56,57,Matt Cassel,DET,36,NaN,2,0,7,17,41.2,59,0,1,3.5,8.4,29.5,26.3,8.8,1
57,58,Joshua Dobbs,PIT,23,NaN,5,0,6,12,50.0,43,0,1,3.6,7.2,8.6,24.0,58.0,0
59,60,Matt Schaub,ATL,37,NaN,3,0,5,7,71.4,20,0,0,2.9,4.0,6.7,74.1,60.6,0
60,61,Robert Griffin,BAL,28,NaN,3,0,2,6,33.3,21,0,0,3.5,10.5,7.0,44.4,2.1,0
61,62,Kyle Lauletta,NYG,23,NaN,2,0,0,5,0.0,0,0,1,0.0,NaN,0.0,0.0,0.1,0
62,63,Jacoby Brissett,IND,26,NaN,4,0,2,4,50.0,2,0,0,0.5,1.0,0.5,56.2,100.0,0
63,64,Johnny Hekker,LAR,28,P,16,0,2,4,50.0,19,0,0,4.8,9.5,1.2,63.5,NaN,0
64,65,Geno Smith,LAC,28,NaN,5,0,1,4,25.0,8,0,0,2.0,8.0,1.6,39.6,0.7,1

In [112]:
# Fill all NaN values with the same value
# Look at the 50th row (as seen in the previous cell) to see the effective changes
fill_zeros = passing_stats.fillna(0)
fill_zeros.loc[[50]]

,Rk,Player,Tm,Age,Pos,G,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sk
50,51,DeShone Kizer,GNB,22,0,3,0,20,42,47.6,187,0,2,4.5,9.4,62.3,40.5,25.2,4

In [118]:
# remove all rows with NaN values
removed_NaN = passing_stats[~passing_stats.isnull().any(axis=1)]
removed_NaN.head()

,Rk,Player,Tm,Age,Pos,G,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sk
0,1,Ben Roethlisberger,PIT,36,QB,16,16,452,675,67.0,5129,34,16,7.6,11.3,320.6,96.5,71.0,24
1,2,Andrew Luck*,IND,29,QB,16,16,430,639,67.3,4593,39,15,7.2,10.7,287.1,98.7,69.4,18
2,3,Matt Ryan,ATL,33,QB,16,16,422,608,69.4,4924,35,7,8.1,11.7,307.8,108.1,68.5,42
3,4,Kirk Cousins,MIN,30,QB,16,16,425,606,70.1,4298,30,10,7.1,10.1,268.6,99.7,58.2,40
4,5,Aaron Rodgers*,GNB,35,QB,16,16,372,597,62.3,4442,25,2,7.4,11.9,277.6,97.6,54.4,49

In [121]:
removed_NaN.shape

(69, 19)

In [124]:
# We can see that rows from the original table have been deleted
removed_NaN.loc[50:60]

,Rk,Player,Tm,Age,Pos,G,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sk
51,52,Mark Sanchez,WAS,32,qb,2,1,19,35,54.3,138,0,3,3.9,7.3,69.0,28.0,4.4,7
52,53,Kyle Allen,CAR,22,qb,2,1,20,31,64.5,266,2,0,8.6,13.3,133.0,113.1,96.4,0
53,54,Matt Barkley,BUF,28,qb,1,1,15,25,60.0,232,2,0,9.3,15.5,232.0,117.4,83.4,1
54,55,Teddy Bridgewater,NOR,26,qb,5,1,14,23,60.9,118,1,1,5.1,8.4,23.6,70.6,39.8,2
58,59,Taysom Hill,NOR,28,te/wr,16,4,3,7,42.9,64,0,1,9.1,21.3,4.0,36.3,41.1,1

In [128]:
# Restart the index!
removed_NaN = removed_NaN.reset_index(drop=True)
removed_NaN.loc[50:60]

,Rk,Player,Tm,Age,Pos,G,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sk
50,52,Mark Sanchez,WAS,32,qb,2,1,19,35,54.3,138,0,3,3.9,7.3,69.0,28.0,4.4,7
51,53,Kyle Allen,CAR,22,qb,2,1,20,31,64.5,266,2,0,8.6,13.3,133.0,113.1,96.4,0
52,54,Matt Barkley,BUF,28,qb,1,1,15,25,60.0,232,2,0,9.3,15.5,232.0,117.4,83.4,1
53,55,Teddy Bridgewater,NOR,26,qb,5,1,14,23,60.9,118,1,1,5.1,8.4,23.6,70.6,39.8,2
54,59,Taysom Hill,NOR,28,te/wr,16,4,3,7,42.9,64,0,1,9.1,21.3,4.0,36.3,41.1,1
55,68,Derrick Henry,TEN,24,RB,16,12,2,3,66.7,14,0,0,4.7,7.0,0.9,77.1,59.3,0
56,72,Julian Edelman,NWE,32,WR,12,12,2,2,100.0,43,0,0,21.5,21.5,3.6,118.7,94.3,0
57,74,Jarvis Landry*,CLE,26,WR,16,14,1,2,50.0,63,0,0,31.5,63.0,3.9,95.8,100.0,0
58,75,Mohamed Sanu,ATL,29,WR,16,16,1,2,50.0,5,1,0,2.5,5.0,0.3,95.8,32.3,0
59,77,Nelson Agholor,PHI,25,WR,16,16,1,1,100.0,15,0,0,15.0,15.0,0.9,118.7,100.0,0
60,78,Danny Amendola,MIA,33,WR,15,15,1,1,100.0,28,1,0,28.0,28.0,1.9,158.3,100.0,0

In [129]:
# Find out which columns have NaN values
passing_stats.columns[passing_stats.isna().any()].tolist()

['Pos', 'Y/C', 'QBR']

In [135]:
# Set up a dictionary to hold the deafult values to fill NaN values
defaults = {
    "Pos" : "NA",
    "Y/C" : 0,
    "QBR" : 0
}

# Fill these values in the table
cleaned = passing_stats.fillna(defaults)
cleaned.loc[[50]]

,Rk,Player,Tm,Age,Pos,G,GS,Cmp,Att,Cmp%,Yds,TD,Int,Y/A,Y/C,Y/G,Rate,QBR,Sk
50,51,DeShone Kizer,GNB,22,NA,3,0,20,42,47.6,187,0,2,4.5,9.4,62.3,40.5,25.2,4